#
# Module manifest for module 'AtlassianPS.Standards'
#
# Generated by: AtlassianPS
#
# Generated on: 06/11/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AtlassianPS.Standards.psm1'

# Version number of this module.
ModuleVersion = '0.1.12'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b558bd8c-dc02-4ff2-96b7-4d2c61d9d103'

# Author of this module
Author = 'AtlassianPS'

# Company or vendor of this module
CompanyName = 'AtlassianPS'

# Copyright statement for this module
Copyright = '(c) 2026 AtlassianPS. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Shared analyzer settings and standards utilities for AtlassianPS modules.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'PSScriptAnalyzer'; RequiredVersion = '1.25.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'PSScriptAnalyzerSettings.psd1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'AtlassianPS','PSScriptAnalyzer','Standards'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AtlassianPS/AtlassianPS.Standards/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/AtlassianPS/AtlassianPS.Standards'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '- Added the `validate-release-intent` GitHub Action to validate PR release and changelog labels before module repositories adopt changelog-fragment based releases without expanding the module export surface.
- Added the `prepare-release-changelog` GitHub Action to prepare release changelog sections from Unreleased entries and changelog fragments, then delete consumed fragments without expanding the module export surface.
- Added label-based continuous release automation that plans releases from merged PR labels, prepares changelog entries, creates annotated tags, publishes to PSGallery, and creates GitHub releases without expanding the module export surface.
- Fixed release-intent validation so release-preparation PRs can delete consumed changelog fragments without treating them as active PR fragments.
- Fixed manual prerelease publishing and removed obsolete publish/package tasks from the Standards build script now that continuous release promotes CI-tested artifacts directly.
* Dogfood release-intent fragment handling (#20, @lipkau)
* Resolve merged release workflow conflicts (#34, @lipkau)'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = 'AtlassianPS'

}

